Repository netgroup/rose-srv6-control-plane, pull requests merged in 2020-06, with the labels that each got.

#32 Fix wrong module names for controller and node manger
  Dockerfile
  control_plane/controller/controller/controller_cli.py
  control_plane/controller/setup.py
  control_plane/node-manager/node_manager/node_mgr.py
  control_plane/node-manager/setup.py
Labels: bug

#30 Clean and improve code
  .gitignore
  control_plane/controller/controller/__init__.py
  control_plane/controller/controller/arangodb_utils.py
  control_plane/controller/controller/cli/__init__.py
  control_plane/controller/controller/cli/cli.py
  control_plane/controller/controller/cli/srv6_cli.py
  control_plane/controller/controller/cli/srv6pm_cli.py
  control_plane/controller/controller/cli/topo_cli.py
  control_plane/controller/controller/controller_cli.py
  control_plane/controller/controller/srv6_pm.py
  control_plane/controller/controller/srv6_utils.py
  control_plane/controller/controller/ti_extraction.py
  control_plane/controller/controller/utils.py
  control_plane/controller/setup.py
  control_plane/examples/arangodb/load_topo_on_arango.py
  control_plane/examples/srv6_pm/srv6_pm_example.py
  control_plane/examples/srv6_tunnels/create_tunnel_r1r4r8.py
  control_plane/examples/srv6_tunnels/create_tunnel_r1r7r8.py
  control_plane/examples/srv6_tunnels/remove_tunnel_r1r4r8.py
  control_plane/examples/srv6_tunnels/remove_tunnel_r1r7r8.py
  control_plane/examples/srv6_tunnels/shift_path.py
  control_plane/node-manager/node_manager/node_mgr.py
  control_plane/node-manager/node_manager/pm_manager.py
  control_plane/node-manager/node_manager/srv6_manager.py
  control_plane/node-manager/node_manager/utils.py
  control_plane/node-manager/setup.py
  control_plane/protos/commons.proto
  control_plane/protos/setup.py
  db_update/db_update/arango_db.py
  db_update/db_update/topo_yaml.py
  db_update/db_update/topo_yaml_2_collections.py
  db_update/db_update/topo_yaml_3_collections.py
Labels: enhancement

#25 Integrate topology extraction and ArangoDB functionalities in the controller
  control_plane/controller/controller/arangodb_utils.py
  control_plane/controller/controller/cli/topo_cli.py
  control_plane/controller/controller/ti_extraction.py
  control_plane/examples/edges.yaml
  control_plane/examples/nodes.yaml
  db_update/db_update/arango_db.py
Labels: enhancement

#50 Add LICENSE file
  LICENSE
Labels: enhancement, low priority

#22 Improve documentation
  README.md
  control_plane/README.md
  control_plane/controller/README.md
  control_plane/controller/controller/cli/README.md
  control_plane/controller/controller/cli/docs/cli.md
  control_plane/controller/controller/cli/docs/srv6.md
  control_plane/controller/controller/cli/docs/srv6pm.md
  control_plane/controller/controller/cli/docs/srv6pm_configuration.md
  control_plane/controller/controller/cli/docs/srv6pm_experiment.md
  control_plane/controller/controller/cli/docs/topology.md
  control_plane/examples/README.md
  control_plane/node-manager/README.md
Labels: documentation

#45 Fix an issue of the topology extraction algorithm entering a endless extraction loop when the controller is not able to reach the nodes
  control_plane/controller/controller/arangodb_utils.py
Labels: bug

#49 Implement persistent command history for the Controller CLI
  control_plane/controller/controller/cli/cli.py
Labels: enhancement

#46 Fix a problem of CLI subsection terminated after command execution
  control_plane/controller/controller/cli/cli.py
Labels: bug

#44 Fix an issue of the controller CLI getting terminated when an exception is raised
  control_plane/controller/controller/cli/cli.py
Labels: bug

#47 Implement arguments tab-completion in Controller CLI
  control_plane/controller/controller/cli/cli.py
  control_plane/controller/controller/cli/srv6_cli.py
  control_plane/controller/controller/cli/srv6pm_cli.py
  control_plane/controller/controller/cli/topo_cli.py
  control_plane/controller/controller/cli/utils.py
Labels: enhancement

#56 Setup Release Drafter github action to automate the creation of release drafts
  .github/label-pr.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/autopep8.yml
  .github/workflows/pr_labeler.yml
  .github/workflows/release-drafter.yml
Labels: github-workflow

#55 Add controller history to .gitignore
  .gitignore
Labels: bug

#57 deploy on docker hub
  .github/workflows/dockerimage.yml
Labels: feature, github-workflow
